---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
    orchestrator-backend-dynamic-integrity: sha512-VIenFStdq9QvvmgmEMG8O7b2wqIebvEcqNeJ9SWZ8jen9t+efTK6D3Rde74LQ1no1QaHLx8RoxNCOuTUEF8O/g==
    orchestrator-backend-dynamic-package: '@redhat/backstage-plugin-orchestrator-backend-dynamic-1.5.1.tgz'
    orchestrator-integrity: sha512-7VOe+XGTUzrdO/av0DNHbydOjB3Lo+XdCs6fj3JVODLP7Ypd3GXHf/nssYxG5ZYC9F1t9MNeguE2bZOB6ckqTA==
    orchestrator-package: '@redhat/backstage-plugin-orchestrator-1.5.1.tgz'
    orchestrator-scaffolder-backend-integrity: sha512-bnVQjVsUZ470Vgm2kd5Lo/bVa2fF0q4GufBDc/8oTQsnP3zZJQqKFvFElBTCjY76RqkECydlvZ1UFybSzvockQ==
    orchestrator-scaffolder-backend-package: '@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic-1.5.1.tgz'
  name: orchestrators.rhdh.redhat.com
spec:
  group: rhdh.redhat.com
  names:
    kind: Orchestrator
    listKind: OrchestratorList
    plural: orchestrators
    singular: orchestrator
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Age
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Status
      jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha3
    schema:
      openAPIV3Schema:
        description: Orchestrator is the Schema for the orchestrators API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: OrchestratorSpec defines the desired state of Orchestrator
            properties:
              argocd:
                default:
                  enabled: false
                description: Configuration for ArgoCD. Optional
                properties:
                  enabled:
                    default: false
                    description: Determines whether to install the ArgoCD plugin and
                      create the orchestrator AppProject
                    type: boolean
                  namespace:
                    description: |-
                      Namespace where the ArgoCD operator is installed and watching for argoapp CR instances
                      Ensure to add the Namespace if ArgoCD is installed
                    type: string
                type: object
              platform:
                description: Configuration for Orchestrator. Optional
                properties:
                  eventing:
                    description: Configuration for existing eventing to be used by
                      sonataflow platform
                    properties:
                      broker:
                        description: Configuration for K-Native broker.
                        properties:
                          name:
                            description: Name of existing Broker instance
                            type: string
                          namespace:
                            description: Namespace of existing Broker instance
                            type: string
                        type: object
                    type: object
                  monitoring:
                    description: Configuration for sonataflow platform monitoring
                    properties:
                      enabled:
                        default: false
                        description: Determines whether to enable the platform monitoring
                        type: boolean
                    type: object
                  namespace:
                    description: Namespace of the workflow pods (Data Index and Job
                      Service) and SonataFlow CR.
                    type: string
                  resources:
                    description: Resource configuration to be used for the data index
                      and job services.
                    properties:
                      limits:
                        description: |-
                          Describes the maximum amount of compute resources allowed.
                          More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        properties:
                          cpu:
                            default: 500m
                            description: Defines the CPU resource limits
                            type: string
                          memory:
                            default: 1Gi
                            description: Defines the memory resource limits
                            type: string
                        type: object
                      requests:
                        description: |-
                          Describe the minimum amount of compute resources required.
                          Requests cannot exceed Limits. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
                        properties:
                          cpu:
                            default: 500m
                            description: Defines the CPU resource limits
                            type: string
                          memory:
                            default: 1Gi
                            description: Defines the memory resource limits
                            type: string
                        type: object
                    type: object
                required:
                - namespace
                type: object
              postgres:
                description: |-
                  Configuration for existing database instance
                  Used by Data index and Job service
                properties:
                  authSecret:
                    description: PostgreSQL connection credentials details
                    properties:
                      name:
                        description: Name of existing secret to use for PostgreSQL
                          credentials.
                        type: string
                      passwordKey:
                        description: Name of key in existing secret to use for PostgreSQL
                          credentials.
                        type: string
                      userKey:
                        description: Name of key in existing secret to use for PostgreSQL
                          credentials.
                        type: string
                    required:
                    - name
                    - passwordKey
                    - userKey
                    type: object
                  database:
                    description: Existing database instance used by data index and
                      job service
                    type: string
                  name:
                    description: Name of the PostgresConfig DB service to be used
                      by platform services
                    type: string
                  namespace:
                    description: Namespace of the PostgresConfig DB service to be
                      used by platform services
                    type: string
                required:
                - authSecret
                - database
                - name
                - namespace
                type: object
              rhdh:
                description: Configuration for RHDH (Backstage).
                properties:
                  devMode:
                    default: false
                    description: |-
                      Determines whether to enable the guest provider in RHDH.
                      This should be used for development purposes ONLY and should not be enabled in production.
                      Defaults to false.
                    type: boolean
                  installOperator:
                    default: false
                    description: |-
                      Determines whether the RHDH operator should be installed
                      This determines the deployment of the RHDH instance.
                      Defaults to false
                    type: boolean
                  name:
                    description: Name of RHDH CR, whether existing or to be installed
                    type: string
                  namespace:
                    description: Namespace of RHDH Instance, whether existing or to
                      be installed
                    type: string
                  plugins:
                    description: Configuration for RHDH Plugins.
                    properties:
                      notificationsEmail:
                        description: Notification email plugin configuration
                        properties:
                          enabled:
                            default: false
                            description: |-
                              Determines whether to install the Notifications Email plugin
                              Requires setting the hostname and credentials in RHDH secret
                              The secret backstage-backend-auth-secret is created as pre-requisite
                              See plugin configuration at https://github.com/backstage/backstage/blob/master/plugins/notifications-backend-module-email/config.d.ts
                            type: boolean
                          port:
                            default: 587
                            description: SMTP server port
                            type: integer
                          replyTo:
                            default: ""
                            description: Email address of the Recipient
                            type: string
                          sender:
                            default: ""
                            description: Email address of the Sender
                            type: string
                        type: object
                    type: object
                required:
                - name
                - namespace
                type: object
              serverless:
                default:
                  installOperator: true
                description: Configuration for Serverless (K-Native) Operator. Optional
                properties:
                  installOperator:
                    default: true
                    description: Determines whether to install the Serverless operator
                    type: boolean
                required:
                - installOperator
                type: object
              serverlessLogic:
                default:
                  installOperator: true
                description: Configuration for ServerlessLogic. Optional
                properties:
                  installOperator:
                    default: true
                    description: Determines whether to install the ServerlessLogic
                      operator
                    type: boolean
                required:
                - installOperator
                type: object
              tekton:
                default:
                  enabled: false
                description: |-
                  Contains the configuration for the infrastructure services required for the Orchestrator to serve workflows
                  by leveraging the OpenShift Serverless and OpenShift Serverless Logic capabilities. Optional
                properties:
                  enabled:
                    default: false
                    description: Determines whether to create the Tekton pipeline
                      resources. Defaults to false.
                    type: boolean
                type: object
            required:
            - postgres
            - rhdh
            type: object
          status:
            description: OrchestratorStatus defines the observed state of Orchestrator
            properties:
              conditions:
                description: |-
                  INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
                  Important: Run "make" to regenerate code after modifying this file
                items:
                  description: "Condition contains details for one aspect of the current
                    state of this API Resource.\n---\nThis struct is intended for
                    direct use as an array at the field path .status.conditions.  For
                    example,\n\n\n\ttype FooStatus struct{\n\t    // Represents the
                    observations of a foo's current state.\n\t    // Known .status.conditions.type
                    are: \"Available\", \"Progressing\", and \"Degraded\"\n\t    //
                    +patchMergeKey=type\n\t    // +patchStrategy=merge\n\t    // +listType=map\n\t
                    \   // +listMapKey=type\n\t    Conditions []metav1.Condition `json:\"conditions,omitempty\"
                    patchStrategy:\"merge\" patchMergeKey:\"type\" protobuf:\"bytes,1,rep,name=conditions\"`\n\n\n\t
                    \   // other fields\n\t}"
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: |-
                        type of condition in CamelCase or in foo.example.com/CamelCase.
                        ---
                        Many .condition.type values are consistent across resources like Available, but because arbitrary conditions can be
                        useful (see .node.status.conditions), the ability to deconflict is important.
                        The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              phase:
                enum:
                - Running
                - Completed
                - Failed
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
